### ISSUE TITLE
Support for Ikea Starkvind

### ISSUE THREAD

**Issue by arjannv** [Smanar/Domoticz-deCONZ#143]
I think that the change in DeConz for the Starkvind requires an update from this plugin. 
https://github.com/dresden-elektronik/deconz-rest-plugin/pull/6124

It now reports as a new ZHAAirPurifier type, while Domoticz-deCONZ only supports the ZHAAirQuality type.

**Comment by Smanar** [comment]
Ha yes right, can you try the beta branch ?
Have added a widget to control the ventilation (with fan icon) and add support for the same than for ZHAAirQuality  for the Starkvind too.

**Comment by arjannv** [comment]
Thanks for the quick response!
I will give it a try. 
For your information: there seems to be an error on line 138 of widget.py
_type  should by _Type I think.

**Comment by Smanar** [comment]
>For your information: there seems to be an error on line 138 of widget.py
_type should by _Type I think.

Exactly, thx ^^, this is untested yet, will be for keypad support

**Comment by arjannv** [comment]
I've tried the update. I'm seeing two devices in Domoticz. 
The things I found so far:
- The sensor value is still in ppb. Acc. to the change in deConz, the new value is in µg/m³. Can I change it manually to µg/m³? (just seeing your edit on the comment)
- The selector switch for the fan has the options Off, Auto, S1, S2, S3, S4, S5. When trying S1 to S5, i'm getting an error: 
`2023-01-16 14:25:37.941 Error: DeConz Hub: deCONZ error :{'error': {'address': '/sensors/153/config/mode', 'description': 'Could not set attribute', 'type': 608}}`
Option Off and Auto are unresponsive. Log:
`2023-01-16 14:28:01.466 DeConz Hub: onCommand called for Unit 229: Parameter 'Set Level', Level: 10, Hue:`
But nothing changes. 
- Maybe it's also nice to add the LED disable switch 0x0003 and the replace filter state 0x0001. These are not showing in Phoscon, only buried deep in the DeCONZ gui. So it will be nice to have these available in Domoticz instead.

**Comment by Smanar** [comment]
Harf, haven't see it use 2 entries.

Have updated the code again, you can update with "git pull"
Can you remove the previously created device and relaod the plugin (domoticz/hardware/deconz/update) ?

>The sensor value is still in ppb. Acc. to the change in deConz, the new value is in µg/m³. Can I change it manually to µg/m³? 

You can, but I have too updated the code, problem idk how deconz will react at character "µ"

>Maybe it's also nice to add the LED disable switch 0x0003 and the replace filter state 0x0001. These are not showing in Phoscon, only buried deep in the DeCONZ gui. So it will be nice to have these available in Domoticz instead

You have a direct acces to the api in domoticz (to see or write values), on Domoticz/Custom/Deconz/Sensor.

If the speed still not working can you make a try with the debug "debug info only" enabled ?

**Comment by arjannv** [comment]
Hi Smanar, thanks for all the work so far. 

> Can you remove the previously created devices and reload the plugin (domoticz/hardware/deconz/update) ?

I've removed all devices related to the Starkvind. 
Now it created a Fan switch and a Group switch with the same functionality (but not working), but not a new PM2.5 sensor.. 

> You can, but I have too updated the code, problem is idk how deconz will react at character "µ"

I can add a custom virtual sensor with the character "µ", could also change the originally created sensor. However, it didn't create a new sensor after removal.

Unfortunately the fan switch still doesn't work. When selecting a mode it gives this in the logs: 
`2023-01-17 08:55:55.866 DeConz Hub: onMessage called

2023-01-17 08:55:55.867 DeConz Hub: ### WebSocket Data : {'attr': {'id': '153', 'lastannounced': None, 'lastseen': '2023-01-17T07:55Z', 'manufacturername': 'IKEA of Sweden', 'modelid': 'STARKVIND Air purifier', 'name': 'PM2.5 Slaapkamer', 'swversion': '1.0.033', 'type': 'ZHAAirPurifier', 'uniqueid': '2c:11:65:ff:fe:b0:88:39-01-fc7d'}, 'e': 'changed', 'id': '153', 'r': 'sensors', 't': 'event', 'uniqueid': '2c:11:65:ff:fe:b0:88:39-01-fc7d'}

2023-01-17 08:55:55.867 DeConz Hub: Send Command /api/13485B9E27/sensors/153 with None (0 in buffer)

2023-01-17 08:55:55.867 DeConz Hub: Making Request: http://127.0.0.1:8080/api/13485B9E27/sensors/153 with params None

2023-01-17 08:55:55.869 DeConz Hub: Request Return: {"config":{"filterlifetime":259200,"ledindication":true,"locked":false,"mode":"off","on":true,"reachable":true},"ep":1,"etag":"b179ede6da8ea670b8c95060e6ae9ba0","lastannounced":null,"lastseen":"2023-01-17T07:55Z","manufacturername":"IKEA of Sweden","modelid":"STARKVIND Air purifier","name":"PM2.5 Slaapkamer","state":{"deviceruntime":690,"filterruntime":690,"lastupdated":"2023-01-16T07:46:05.161","replacefilter":false,"speed":20},"swversion":"1.0.033","type":"ZHAAirPurifier","uniqueid":"2c:11:65:ff:fe:b0:88:39-01-fc7d"}

2023-01-17 08:55:55.869 DeConz Hub: Classic Data : {'config': {'filterlifetime': 259200, 'ledindication': True, 'locked': False, 'mode': 'off', 'on': True, 'reachable': True}, 'ep': 1, 'etag': 'b179ede6da8ea670b8c95060e6ae9ba0', 'lastannounced': None, 'lastseen': '2023-01-17T07:55Z', 'manufacturername': 'IKEA of Sweden', 'modelid': 'STARKVIND Air purifier', 'name': 'PM2.5 Slaapkamer', 'state': {'deviceruntime': 690, 'filterruntime': 690, 'lastupdated': '2023-01-16T07:46:05.161', 'replacefilter': False, 'speed': 20}, 'swversion': '1.0.033', 'type': 'ZHAAirPurifier', 'uniqueid': '2c:11:65:ff:fe:b0:88:39-01-fc7d'}

2023-01-17 08:55:55.869 DeConz Hub: ### Device > 153 Name:PM2.5 Slaapkamer Type:ZHAAirPurifier Details:{'deviceruntime': 690, 'filterruntime': 690, 'lastupdated': '2023-01-16T07:46:05.161', 'replacefilter': False, 'speed': 20} and {'filterlifetime': 259200, 'ledindication': True, 'locked': False, 'mode': 'off', 'on': True, 'reachable': True}

2023-01-17 08:55:55.869 DeConz Hub: onMessage called

2023-01-17 08:55:55.869 DeConz Hub: ### WebSocket Data : {'attr': {'id': '154', 'lastannounced': None, 'lastseen': '2023-01-17T07:55Z', 'manufacturername': 'IKEA of Sweden', 'modelid': 'STARKVIND Air purifier', 'name': 'PM2.5 Slaapkamer', 'swversion': '1.0.033', 'type': 'ZHAAirQuality', 'uniqueid': '2c:11:65:ff:fe:b0:88:39-02-fc7d'}, 'e': 'changed', 'id': '154', 'r': 'sensors', 't': 'event', 'uniqueid': '2c:11:65:ff:fe:b0:88:39-02-fc7d'}

2023-01-17 08:55:55.869 Status: DeConz Hub: Adding missing device: 153 Type:ZHAAirPurifier

2023-01-17 08:55:55.867 Error: DeConz Hub: Websocket error, unknown device > 153 (sensors) Asking for information

2023-01-17 08:55:56.019 DeConz Hub: onMessage called

2023-01-17 08:55:56.019 DeConz Hub: ### WebSocket Data : {'attr': {'id': '3', 'lastannounced': None, 'lastseen': '2023-01-17T07:55Z', 'manufacturername': 'Philips', 'modelid': 'ROM001', 'name': 'Knop Babykamer', 'swversion': '2.25.0_r30044', 'type': 'ZHASwitch', 'uniqueid': '00:17:88:01:06:54:ea:66-01-fc00'}, 'e': 'changed', 'id': '3', 'r': 'sensors', 't': 'event', 'uniqueid': '00:17:88:01:06:54:ea:66-01-fc00'}

2023-01-17 08:55:57.072 DeConz Hub: onHeartbeat called

2023-01-17 08:55:57.373 DeConz Hub: onCommand called for Unit 228: Parameter 'Set Level', Level: 10, Hue:

2023-01-17 08:55:57.373 DeConz Hub: Send Command /api/13485B9E27/sensors/153/config with {'mode': 'auto'} (0 in buffer)

2023-01-17 08:55:57.373 DeConz Hub: Making Request: http://127.0.0.1:8080/api/13485B9E27/sensors/153/config with params {'mode': 'auto'}

2023-01-17 08:55:57.377 DeConz Hub: Request Return: [{"success":{"/sensors/153/config/mode":"auto"}}]

2023-01-17 08:55:57.377 DeConz Hub: Classic Data : [{'success': {'/sensors/153/config/mode': 'auto'}}]

2023-01-17 08:55:57.377 DeConz Hub: onMessage called

2023-01-17 08:55:57.377 DeConz Hub: ### WebSocket Data : {'config': {'filterlifetime': 259200, 'ledindication': True, 'locked': False, 'mode': 'auto', 'on': True, 'reachable': True}, 'e': 'changed', 'id': '153', 'r': 'sensors', 't': 'event', 'uniqueid': '2c:11:65:ff:fe:b0:88:39-01-fc7d'}

2023-01-17 08:55:57.377 DeConz Hub: Send Command /api/13485B9E27/sensors/153 with None (0 in buffer)

2023-01-17 08:55:57.377 DeConz Hub: Making Request: http://127.0.0.1:8080/api/13485B9E27/sensors/153 with params None

2023-01-17 08:55:57.380 DeConz Hub: Request Return: {"config":{"filterlifetime":259200,"ledindication":true,"locked":false,"mode":"auto","on":true,"reachable":true},"ep":1,"etag":"5f285675e0bf8aa45b24e91f36341d73","lastannounced":null,"lastseen":"2023-01-17T07:55Z","manufacturername":"IKEA of Sweden","modelid":"STARKVIND Air purifier","name":"PM2.5 Slaapkamer","state":{"deviceruntime":690,"filterruntime":690,"lastupdated":"2023-01-16T07:46:05.161","replacefilter":false,"speed":20},"swversion":"1.0.033","type":"ZHAAirPurifier","uniqueid":"2c:11:65:ff:fe:b0:88:39-01-fc7d"}

2023-01-17 08:55:57.380 DeConz Hub: Classic Data : {'config': {'filterlifetime': 259200, 'ledindication': True, 'locked': False, 'mode': 'auto', 'on': True, 'reachable': True}, 'ep': 1, 'etag': '5f285675e0bf8aa45b24e91f36341d73', 'lastannounced': None, 'lastseen': '2023-01-17T07:55Z', 'manufacturername': 'IKEA of Sweden', 'modelid': 'STARKVIND Air purifier', 'name': 'PM2.5 Slaapkamer', 'state': {'deviceruntime': 690, 'filterruntime': 690, 'lastupdated': '2023-01-16T07:46:05.161', 'replacefilter': False, 'speed': 20}, 'swversion': '1.0.033', 'type': 'ZHAAirPurifier', 'uniqueid': '2c:11:65:ff:fe:b0:88:39-01-fc7d'}

2023-01-17 08:55:57.380 DeConz Hub: ### Device > 153 Name:PM2.5 Slaapkamer Type:ZHAAirPurifier Details:{'deviceruntime': 690, 'filterruntime': 690, 'lastupdated': '2023-01-16T07:46:05.161', 'replacefilter': False, 'speed': 20} and {'filterlifetime': 259200, 'ledindication': True, 'locked': False, 'mode': 'auto', 'on': True, 'reachable': True}

2023-01-17 08:55:57.342 Status: User: Admin (IP: 10.0.0.101) initiated a switch command (725/DeConz Hub - PM2.5 Slaapkamer/Set Level)

2023-01-17 08:55:57.380 Status: DeConz Hub: Adding missing device: 153 Type:ZHAAirPurifier

2023-01-17 08:55:57.377 Error: DeConz Hub: Websocket error, unknown device > 153 (sensors) Asking for information`

DeCONZ ID 153 = ZHAAirPurifier (Fan and filter info)
DeCONZ ID 154 = ZHAAirQuality (PM2.5 sensor) 
Domoticz ID 228 = Fan Switch
Domoticz ID 229 = Group Switch

It's really weird this isn't working..  The request is on the correct entry, with an accepted value. 

Only values S1 to S5 are still wrong I think. 
In the GUI, the accepted values are: 
Off, Low, Medium, High, On, Auto, Smart
![strkvnd](https://user-images.githubusercontent.com/43266823/212845150-0e6db8c6-fceb-495d-84a0-ffe70a1f3974.jpg)


When using the Group switch also nothing happens but, the log is a lot shorter
`2023-01-17 08:54:50.679 DeConz Hub: onCommand called for Unit 229: Parameter 'Set Level', Level: 10, Hue:

2023-01-17 08:54:50.677 Status: User: Admin (IP: 10.0.0.101) initiated a switch command (726/DeConz Hub - PM2.5 Slaapkamer/Set Level)

2023-01-17 08:54:50.679 Error: DeConz Hub: This device doesn't support action`

> You have a direct acces to the api in domoticz (to see or write values), on Domoticz/Custom/Deconz/Sensor.

Oh wow, learned something cool today :) Thanks, didn't knew that was possible.

**Comment by Smanar** [comment]
>Oh wow, learned something cool today :) Thanks, didn't knew that was possible

Yeah and can too use that https://github.com/Smanar/Domoticz-deCONZ/wiki/Example-to-use-custom-widget-to-act-direclty-on-the-deconz-API.

Some setting are used only 1 time by year, so I prefer don't use a widget just for that.

Edit:
So I have found a problem
The device was not added 
```
2023-01-17 08:55:57.380 Status: DeConz Hub: Adding missing device: 153 Type:ZHAAirPurifier
2023-01-17 08:55:57.377 Error: DeConz Hub: Websocket error, unknown device > 153 (sensors) Asking for informatio
```

So I have made a complete rollback, so new code (with new problems)
With it you need to have

- ZHAAirQuality > a custom widget, I m checking for the presence of "state/pm2_5" for the unity, idk why this part is not working, but Domoticz have a native widget for air quality, working with ppm, I need to see if I can make a convertion.
- ZHAAirPurifier > A custom widget for speed
- ZHAAirPurifier  > A selector switch to set the speed.

And have checked code again, the API don't use same value in the GUI https://github.com/dresden-elektronik/deconz-rest-plugin/blob/12f7f3610c985c47efe6980a205672925d0c82ae/devices/ikea/starkvind_write_target_mode.js

Sorry again for all retries.

**Comment by arjannv** [comment]
No problem :) Happy to help. 

It added another selector switch, but it gives an error every few seconds: 
`2023-01-17 13:26:44.119 Error: DeConz Hub: Call to function 'onHeartbeat' failed, exception details:`
`2023-01-17 13:26:44.119 Error: DeConz Hub: Traceback (most recent call last):`
`2023-01-17 13:26:44.119 Error: DeConz Hub: File "/home/arjan/domoticz/plugins/Domoticz-deCONZ/plugin.py", line 1146, in onHeartbeat`
`2023-01-17 13:26:44.119 Error: DeConz Hub: _plugin.onHeartbeat()`
`2023-01-17 13:26:44.119 Error: DeConz Hub: File "/home/arjan/domoticz/plugins/Domoticz-deCONZ/plugin.py", line 500, in onHeartbeat`
`2023-01-17 13:26:44.119 Error: DeConz Hub: self.ManageInit()`
`2023-01-17 13:26:44.119 Error: DeConz Hub: File "/home/arjan/domoticz/plugins/Domoticz-deCONZ/plugin.py", line 558, in ManageInit`
`2023-01-17 13:26:44.119 Error: DeConz Hub: self.SendCommand("/api/" + Parameters["Mode2"] + "/" + self.INIT_STEP[0] + "/")`
`2023-01-17 13:26:44.119 Error: DeConz Hub: File "/home/arjan/domoticz/plugins/Domoticz-deCONZ/plugin.py", line 1039, in SendCommand`
`2023-01-17 13:26:44.119 Error: DeConz Hub: self.UpdateBuffer()`
`2023-01-17 13:26:44.119 Error: DeConz Hub: File "/home/arjan/domoticz/plugins/Domoticz-deCONZ/plugin.py", line 1080, in UpdateBuffer`
`2023-01-17 13:26:44.119 Error: DeConz Hub: self.NormalConnexion(_Data)`
`2023-01-17 13:26:44.119 Error: DeConz Hub: File "/home/arjan/domoticz/plugins/Domoticz-deCONZ/plugin.py", line 799, in NormalConnexion`
`2023-01-17 13:26:44.119 Error: DeConz Hub: self.InitDomoticzDB(i,_Data[i],self.INIT_STEP[0])`
`2023-01-17 13:26:44.119 Error: DeConz Hub: File "/home/arjan/domoticz/plugins/Domoticz-deCONZ/plugin.py", line 735, in InitDomoticzDB`
`2023-01-17 13:26:44.119 Error: DeConz Hub: UpdateDevice(key, Type_device, kwarg, self.SpecialDeviceList)`
`2023-01-17 13:26:44.119 Error: DeConz Hub: File "/home/arjan/domoticz/plugins/Domoticz-deCONZ/plugin.py", line 1299, in UpdateDevice`
`2023-01-17 13:26:44.119 Error: DeConz Hub: UpdateDevice_Special(_id, _type, kwarg, d)`
`2023-01-17 13:26:44.119 Error: DeConz Hub: File "/home/arjan/domoticz/plugins/Domoticz-deCONZ/plugin.py", line 1286, in UpdateDevice_Special`
`2023-01-17 13:26:44.119 Error: DeConz Hub: UpdateDeviceProc(kwarg2,Unit2)`
`2023-01-17 13:26:44.119 Error: DeConz Hub: File "/home/arjan/domoticz/plugins/Domoticz-deCONZ/plugin.py", line 1317, in UpdateDeviceProc`
`2023-01-17 13:26:44.119 Error: DeConz Hub: if kwarg[a] != getattr(Devices[Unit], a ):`
`2023-01-17 13:26:44.119 Error: DeConz Hub: AttributeError: 'Domoticz.Device' object has no attribute 'speed'`

**Comment by arjannv** [comment]
Great! Selector switch now works! 
Still no PM2.5 sensor. will re-add the device to check if it helps. 
Will report back :)

**Comment by arjannv** [comment]
Ok, removed all stuff and re-added the Starkvind to DeCONZ. 
It created a Fan selector switch and two sensors. See picture below. 
1st is the PM2.5 level (in m/s???) and 2nd is another custom sensor with a value in m/s. 
![strkvnd](https://user-images.githubusercontent.com/43266823/212929011-ae03e2e1-2e6f-49d6-9a55-a330b4c678c5.jpg)
The first sensor works perfectly, only the units are in m/s. 
I really don't know which sensor the second one is. In the picture it shows a value of 20 m/s, but I can't find an attribute with a value of 20. 
![image](https://user-images.githubusercontent.com/43266823/212931623-cbdd2461-674c-44a2-9605-0975c1e5f773.png)


The selector switch works (kind of). When I select a option "Auto, S1-S5", the Starkvind goes to that option (Auto or S1-S5). But the switch in Domoticz jumps always to S1. This is with all options except "Off".

**Comment by Smanar** [comment]
Lol, seriously there is something magic on thoses custom sensors ....

So yes the "speed" is the attribute 0x0007 but I don't have found information about the "value", for me a speed is in m/s and its the value displayed in the API, raw value.
The "speed" return can be different from the value you set in "mode" yes, so for me it's more usefull than the filterlifetime, and move more often.
From here the value can reach 100 https://github.com/dresden-elektronik/deconz-rest-plugin/pull/6118#issue-1262201522

So new modifications :
- I m using a fake unit for Pm2.5, to be sure the problem is not from the character  "µ"
- Try something for the return state of the config/mode, when you press the button it send a request, this part work, after deconz make a return by websoket, and I use this value to update the widget, and it's this part that failled

You can just remove the pm2.5 sensor for this try, no change on others.

**Comment by arjannv** [comment]
Thanks for the modifications. 

Yes, it is a very nice value to have, the speed. It would be nice to use it for automations, limiting the speed when the mode is on "auto" for instance. 
The other values are only used rarely I suspect.

Fan selector switch is working now! The mode now is the same in Domoticz and on the Starkvind. 
The PM2.5 sensor was recreated automatically with m/s. It was possible to change this manually to μg/m³.

**Comment by Smanar** [comment]
>The PM2.5 sensor was recreated automatically with m/s

Seriously ?

```
    elif _Type == 'ZHAAirQuality':
        #kwarg['TypeName'] = 'Air Quality'
        kwarg['TypeName'] = 'Custom'
        if opt == 1:
            kwarg['Options'] = {"Custom": ("1;abcdef")}
        else:
            kwarg['Options'] = {"Custom": ("1;ppb")}
```

How you can have "m/s" ?
You are sure you deleting the good one ?

It's magic, you are sure having the same code in the file widget.py ?

**Comment by arjannv** [comment]
Hmm, strange. 
The weird thing is that they are both added as a ZHAAirPurifier
`2023-01-18 16:32:39.165 Status: DeConz Hub: ### Create Device 2c:11:65:ff:fe:b0:88:39-01-fc7d > Lucht Slaapkamer (ZHAAirPurifier) as Unit 229`
`2023-01-18 16:32:39.169 Status: DeConz Hub: ### Create Device 2c:11:65:ff:fe:b0:88:39-02-fc7d > Lucht Slaapkamer (ZHAAirPurifier) as Unit 230`
So the end up both with m/s as unit.

**Comment by Smanar** [comment]
Ha ^^ finally :)
