### ISSUE TITLE
Issue with latest version of the plugin (beta), stable is working fine

### ISSUE THREAD

**Issue by geschriever** [Smanar/Domoticz-deCONZ#166]
Hi @Smanar,
I'm encountering problems when I update the repository to the latest version and get a lot of errors.
The previous version is working fine!
I'm using a Raspberry 3B with bullseye (up-to-date) and python 3.9.2, Domoticz version 15937.
The zigbee stick is Conbee-II and also on latest version of Phoscon.
Phoscon is working correctly so the issue is in this deConz plugin. Gateway version: 2.26.3 and firmware 26780700

I cannot find the issue, do you have any clue what is going on?

The error log is after enabling the deConz plugin:
Error: deConz_plugin: Call to function 'onHeartbeat' failed, exception details:
2024-04-16 11:52:22.362 Error: deConz_plugin: Traceback (most recent call last):
2024-04-16 11:52:22.362 Error: deConz_plugin: File "/home/pi/domoticz/plugins/Domoticz-deCONZ/plugin.py", line 1243, in onHeartbeat
2024-04-16 11:52:22.362 Error: deConz_plugin: _plugin.onHeartbeat()
2024-04-16 11:52:22.362 Error: deConz_plugin: File "/home/pi/domoticz/plugins/Domoticz-deCONZ/plugin.py", line 538, in onHeartbeat
2024-04-16 11:52:22.362 Error: deConz_plugin: self.ManageInit()
2024-04-16 11:52:22.362 Error: deConz_plugin: File "/home/pi/domoticz/plugins/Domoticz-deCONZ/plugin.py", line 601, in ManageInit
2024-04-16 11:52:22.362 Error: deConz_plugin: self.SendCommand("/api/" + Parameters["Mode2"] + "/" + self.INIT_STEP[0] + "/")
2024-04-16 11:52:22.362 Error: deConz_plugin: File "/home/pi/domoticz/plugins/Domoticz-deCONZ/plugin.py", line 1130, in SendCommand
2024-04-16 11:52:22.362 Error: deConz_plugin: self.UpdateBuffer()
2024-04-16 11:52:22.362 Error: deConz_plugin: File "/home/pi/domoticz/plugins/Domoticz-deCONZ/plugin.py", line 1171, in UpdateBuffer
2024-04-16 11:52:22.362 Error: deConz_plugin: self.NormalConnexion(_Data)
2024-04-16 11:52:22.362 Error: deConz_plugin: File "/home/pi/domoticz/plugins/Domoticz-deCONZ/plugin.py", line 864, in NormalConnexion
2024-04-16 11:52:22.362 Error: deConz_plugin: self.ReadConfig(_Data)
2024-04-16 11:52:22.362 Error: deConz_plugin: File "/home/pi/domoticz/plugins/Domoticz-deCONZ/plugin.py", line 961, in ReadConfig
2024-04-16 11:52:22.362 Error: deConz_plugin: self.ManageInit(True)
2024-04-16 11:52:22.362 Error: deConz_plugin: File "/home/pi/domoticz/plugins/Domoticz-deCONZ/plugin.py", line 601, in ManageInit
2024-04-16 11:52:22.362 Error: deConz_plugin: self.SendCommand("/api/" + Parameters["Mode2"] + "/" + self.INIT_STEP[0] + "/")
2024-04-16 11:52:22.362 Error: deConz_plugin: File "/home/pi/domoticz/plugins/Domoticz-deCONZ/plugin.py", line 1130, in SendCommand
2024-04-16 11:52:22.362 Error: deConz_plugin: self.UpdateBuffer()
2024-04-16 11:52:22.362 Error: deConz_plugin: File "/home/pi/domoticz/plugins/Domoticz-deCONZ/plugin.py", line 1171, in UpdateBuffer
2024-04-16 11:52:22.362 Error: deConz_plugin: self.NormalConnexion(_Data)
2024-04-16 11:52:22.362 Error: deConz_plugin: File "/home/pi/domoticz/plugins/Domoticz-deCONZ/plugin.py", line 883, in NormalConnexion
2024-04-16 11:52:22.362 Error: deConz_plugin: self.ManageInit(True)
2024-04-16 11:52:22.362 Error: deConz_plugin: File "/home/pi/domoticz/plugins/Domoticz-deCONZ/plugin.py", line 601, in ManageInit
2024-04-16 11:52:22.362 Error: deConz_plugin: self.SendCommand("/api/" + Parameters["Mode2"] + "/" + self.INIT_STEP[0] + "/")
2024-04-16 11:52:22.362 Error: deConz_plugin: File "/home/pi/domoticz/plugins/Domoticz-deCONZ/plugin.py", line 1130, in SendCommand
2024-04-16 11:52:22.362 Error: deConz_plugin: self.UpdateBuffer()

**Comment by ryanrudak** [comment]
same issue here  - try to remove the special setting ENABLEBATTERYWIDGET and try again.
For me this works.

Now only these errors can be seen in the log:
2024-04-16 19:38:07.411 Error: zigbee: Unknow device type CLIPDaylightOffset
2024-04-16 19:38:07.451 Error: zigbee: Unknow device type CLIPDaylightOffset
2024-04-16 19:38:07.452 Error: zigbee: Unknow device type CLIPDaylightOffset
2024-04-16 19:38:07.453 Error: zigbee: Unknow device type CLIPDaylightOffset

**Comment by Smanar** [comment]
Thx @ryanrudak with your information I  was able to reproduce the issue, but it's probably from domoticz, or I have skipped an update.
Have open an issue on their github https://github.com/domoticz/domoticz/issues/6057
But for the moment the better workaround is removing ENABLEBATTERYWIDGET .

Have updated the code for the CLIPDaylightOffset issue, still on test on my side.

**Comment by Smanar** [comment]
It's ok gizmocuz have corrected the issue.
I m using ATM the version 15952 without problem.
