### ISSUE TITLE
After Update, all kind of Errors

### ISSUE THREAD

**Issue by Luigi-01** [Smanar/Domoticz-deCONZ#167]
deConz versions 2.26.3 
Conbee III firmware 26510900
Today I did an update of the Plugins and the system is generating many errors.
I continues to generate many errors
Before the update I had almost no error, just missed calls, no other errors.

 2024-04-27 09:46:23.485 Error: Zigbee: deCONZ not ready
2024-04-27 09:46:23.485 Error: Zigbee: deCONZ not ready
2024-04-27 09:46:23.485 Error: Zigbee: deCONZ not ready
2024-04-27 09:46:23.485 Error: Zigbee: deCONZ not ready
2024-04-27 09:46:26.146 Error: Zigbee: Unknow device type CLIPDaylightOffset
2024-04-27 09:46:26.146 Error: Zigbee: Unknow device type CLIPDaylightOffset
2024-04-27 09:46:26.147 Error: Zigbee: Unknow device type CLIPDaylightOffset
2024-04-27 09:46:26.147 Error: Zigbee: Unknow device type CLIPDaylightOffset
2024-04-27 09:46:26.148 Error: Zigbee: Call to function 'onHeartbeat' failed, exception details:
2024-04-27 09:46:26.148 Error: Zigbee: Traceback (most recent call last):
2024-04-27 09:46:26.148 Error: Zigbee: File "/home/milaan/domoticz/plugins/Domoticz-deCONZ/plugin.py", line 1243, in onHeartbeat
2024-04-27 09:46:26.148 Error: Zigbee: _plugin.onHeartbeat()
2024-04-27 09:46:26.148 Error: Zigbee: File "/home/milaan/domoticz/plugins/Domoticz-deCONZ/plugin.py", line 538, in onHeartbeat
2024-04-27 09:46:26.148 Error: Zigbee: self.ManageInit()
2024-04-27 09:46:26.148 Error: Zigbee: File "/home/milaan/domoticz/plugins/Domoticz-deCONZ/plugin.py", line 601, in ManageInit
2024-04-27 09:46:26.148 Error: Zigbee: self.SendCommand("/api/" + Parameters["Mode2"] + "/" + self.INIT_STEP[0] + "/")
2024-04-27 09:46:26.148 Error: Zigbee: File "/home/milaan/domoticz/plugins/Domoticz-deCONZ/plugin.py", line 1130, in SendCommand
2024-04-27 09:46:26.148 Error: Zigbee: self.UpdateBuffer()
2024-04-27 09:46:26.148 Error: Zigbee: File "/home/milaan/domoticz/plugins/Domoticz-deCONZ/plugin.py", line 1171, in UpdateBuffer
2024-04-27 09:46:26.148 Error: Zigbee: self.NormalConnexion(_Data)
2024-04-27 09:46:26.148 Error: Zigbee: File "/home/milaan/domoticz/plugins/Domoticz-deCONZ/plugin.py", line 880, in NormalConnexion
2024-04-27 09:46:26.148 Error: Zigbee: self.InitDomoticzDB(i,_Data[i],self.INIT_STEP[0])
2024-04-27 09:46:26.148 Error: Zigbee: File "/home/milaan/domoticz/plugins/Domoticz-deCONZ/plugin.py", line 643, in InitDomoticzDB
2024-04-27 09:46:26.148 Error: Zigbee: kwarg.update(ProcessAllState(StateList,Model,0))
2024-04-27 09:46:26.148 Error: Zigbee: File "/home/milaan/domoticz/plugins/Domoticz-deCONZ/fonctions.py", line 379, in ProcessAllState
2024-04-27 09:46:26.148 Error: Zigbee: kwarg.update(ReturnUpdateValue('airqualityppb', data['measured_value'], option))
2024-04-27 09:46:26.148 Error: Zigbee: File "/home/milaan/domoticz/plugins/Domoticz-deCONZ/fonctions.py", line 702, in ReturnUpdateValue
2024-04-27 09:46:26.148 Error: Zigbee: kwarg['nValue'] = int(val)
2024-04-27 09:46:26.148 Error: Zigbee: ValueError: invalid literal for int() with base 10: '7.31'
2024-04-27 09:46:29.018 Error: Zigbee: deCONZ not ready
2024-04-27 09:46:36.115 Error: Zigbee: Unknow device type CLIPDaylightOffset
2024-04-27 09:46:36.115 Error: Zigbee: Unknow device type CLIPDaylightOffset
2024-04-27 09:46:36.115 Error: Zigbee: Unknow device type CLIPDaylightOffset
2024-04-27 09:46:36.115 Error: Zigbee: Unknow device type CLIPDaylightOffset
2024-04-27 09:46:36.117 Error: Zigbee: Call to function 'onHeartbeat' failed, exception details:
2024-04-27 09:46:36.117 Error: Zigbee: Traceback (most recent call last):
2024-04-27 09:46:36.117 Error: Zigbee: File "/home/milaan/domoticz/plugins/Domoticz-deCONZ/plugin.py", line 1243, in onHeartbeat
2024-04-27 09:46:36.117 Error: Zigbee: _plugin.onHeartbeat()
2024-04-27 09:46:36.117 Error: Zigbee: File "/home/milaan/domoticz/plugins/Domoticz-deCONZ/plugin.py", line 538, in onHeartbeat
2024-04-27 09:46:36.117 Error: Zigbee: self.ManageInit()
2024-04-27 09:46:36.117 Error: Zigbee: File "/home/milaan/domoticz/plugins/Domoticz-deCONZ/plugin.py", line 601, in ManageInit
2024-04-27 09:46:36.117 Error: Zigbee: self.SendCommand("/api/" + Parameters["Mode2"] + "/" + self.INIT_STEP[0] + "/")
2024-04-27 09:46:36.117 Error: Zigbee: File "/home/milaan/domoticz/plugins/Domoticz-deCONZ/plugin.py", line 1130, in SendCommand
2024-04-27 09:46:36.117 Error: Zigbee: self.UpdateBuffer()
2024-04-27 09:46:36.117 Error: Zigbee: File "/home/milaan/domoticz/plugins/Domoticz-deCONZ/plugin.py", line 1171, in UpdateBuffer
2024-04-27 09:46:36.117 Error: Zigbee: self.NormalConnexion(_Data)
2024-04-27 09:46:36.117 Error: Zigbee: File "/home/milaan/domoticz/plugins/Domoticz-deCONZ/plugin.py", line 880, in NormalConnexion
2024-04-27 09:46:36.117 Error: Zigbee: self.InitDomoticzDB(i,_Data[i],self.INIT_STEP[0])
2024-04-27 09:46:36.117 Error: Zigbee: File "/home/milaan/domoticz/plugins/Domoticz-deCONZ/plugin.py", line 643, in InitDomoticzDB
2024-04-27 09:46:36.117 Error: Zigbee: kwarg.update(ProcessAllState(StateList,Model,0))
2024-04-27 09:46:36.117 Error: Zigbee: File "/home/milaan/domoticz/plugins/Domoticz-deCONZ/fonctions.py", line 379, in ProcessAllState
2024-04-27 09:46:36.117 Error: Zigbee: kwarg.update(ReturnUpdateValue('airqualityppb', data['measured_value'], option))
2024-04-27 09:46:36.117 Error: Zigbee: File "/home/milaan/domoticz/plugins/Domoticz-deCONZ/fonctions.py", line 702, in ReturnUpdateValue
2024-04-27 09:46:36.117 Error: Zigbee: kwarg['nValue'] = int(val)
2024-04-27 09:46:36.117 Error: Zigbee: ValueError: invalid literal for int() with base 10: '7.31'

**Comment by Smanar** [comment]
Hello, at least some of then are already corrected, can you try the beta branch ?

Just go in plugin folder, then use
```
git pull
git checkout beta
git pull
```
then in Domoticz/hardware/deconz/update to restart it.


If all is fine for you after I will update the stable.

**Comment by Luigi-01** [comment]
Hi Amanda,

I did what you suggested and it worked.
Thanks.

The only strange thing was, he did not change any thing.
I am a little confused, no change but it works now fine.

Have a nice day,

Op 27 apr. 2024 11:06, om 11:06, Smanar ***@***.***> schreef:

**Comment by Smanar** [comment]
>The only strange thing was, he did not change any thing.

Somes issues are from deconz upgrade.
Thx for return, I will update immedialty the stable for others users.
